import { Geist, Geist_Mono, Noto_Sans_Bengali } from "next/font/google"; // Import Noto Sans Bengali
import "./globals.css";
import AppNavbar from "@/component/Navbar/AppNavbar";

// Geist font setup
const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

// Geist Mono font setup
const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

// Noto Sans Bengali font setup
const notoSansBengali = Noto_Sans_Bengali({
    variable: "--font-noto-sans-bengali",
    subsets: ["bengali"], // Specify Bengali subset
});

// Metadata
export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
        <head>
            <meta charSet="UTF-8" />
        </head>
        <body
            className={`${geistSans.variable} ${geistMono.variable} ${notoSansBengali.variable} antialiased`}
        >
        <AppNavbar>{children}</AppNavbar>
        </body>
        </html>
    );
}
