import { Poppins, Noto_Sans_Bengali } from "next/font/google";
import "./globals.css";
import AppNavbar from "@/component/Navbar/AppNavbar";

// Poppins font setup
const poppins = Poppins({
    variable: "--font-poppins",
    subsets: ["latin"],
    weight: ['400', '700'], // optional: regular + bold
});

// Noto Sans Bengali font setup
const notoSansBengali = Noto_Sans_Bengali({
    variable: "--font-noto-sans-bengali",
    subsets: ["bengali"],
    weight: ['400', '700'], // optional: regular + bold
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="bn">
        <body className={`${poppins.variable} ${notoSansBengali.variable} antialiased`}>
        <AppNavbar>{children}</AppNavbar>
        </body>
        </html>
    );
}
